<?php

/**
 * Created by PhpStorm.
 * User: Harry Anand
 * Date: 8/25/2016
 * Time: 4:12 PM
 */
return [
    'user_profile' => [
        'type' => [
            'user' => 0,
            'owner' => 1,
            'tenant' => 2,
            'agent' => 3,
            'builder' => 4,
            'landlord' => 5,
            'seller' => 6,
            'realtor' => 7,
        ],
        'default_company' => 0,
    ],
    'pro_type' => [
        'rent' => 1,
        'lease' => 2,
        'sell' => 3,
    ],
    'google_map_api' => 'AIzaSyCkpTXMal7PwmYsR2BOLmfFbrJQp6hZ17I',
    'approved' => 1,
    'unapproved' => 0,
    'published' => 1,
    'unpublished' => 0,
    'country_id' => 86,
    'currency' => 24,
    'access' => 1,
    'unregistered' => 1,
    'owner' => 1,
    'tenant' => 2,
    'current_date' => date("Y-m-d"),
    'current_date_time' => date("Y-m-d", time()),
    'like_accept' => 1,
    'like_reject' => 2,
    'item_per_page' => 10,
    'booking_active' => 1,
    'booking_inactive' => 2,
    'booking_room' => 1,
    'booking_bed' => 2,
    'booking_type_default' => 0,
    'location_per_page' => 12,
    'society_per_page' => 12,
    'residential' => 16,
    'commercial' => 97,
    'tinyUrl' => [
        'url' => 'https://www.googleapis.com/urlshortener/v1/url',
        'key' => 'AIzaSyDvEcrNUFArog91LBygcXOq7m5ZpOW-mBw',
        'reference_url' => '//101lease.com/details/101L-'
    ],
    'smsGetway' => [
        'test' => [
            'url' => 'http://sms.hspsms.com/sendSMS',
            'key' => '65b8475e-6df8-4d19-95e0-56f7d979dc8e',
            'username' => 'hspdemo',
            'sendername' => 'hspsms',
            'smstype' => 'TRANS',
        ],
        'live' => [
            'url' => 'http://sms.hspsms.com/sendSMS',
            'key' => '1874438a-8513-4a4b-a3ed-2dde612e2655',
            'username' => 'civilmachines',
            'sendername' => 'ILEASE',
            'smstype' => 'TRANS',
        ]
    ],
    'crm' => [
        'url' => 'https://www.101lease.com/crm/modules/Webforms/capture.php',
        'crm_auth_api' => 'http://revcrm.local/api/v1/webregister',
//        'key' => '5d6c0a7f-226a-44e7-8d0c-cccb6d6d6390',
//        'username' => 'hspdemo',
//        'sendername' => 'hspsms',
//        'smstype' => 'TRANS',
    ],
    'itr_image_category' => [
        'form_16' => 1,
        'loan_certificate' => 2,
        'interest_certificate' => 3,
        'claim_80C' => 4,
        'claim_80D' => 5,
        'claim_80G' => 6,
        'other_deduction' => 7,
        'tax_challan' => 8,
        'form_26A' => 9,
        'co_owned_prop_image' => 10,
        'partner_firm_image' => 11,
        'capital_gain_image' => 12,
        'othr_source_incm_image' => 13,
        'immovable_asset_image' => 14,
        'outside_income_image' => 15,
        'assets_partner_image' => 16,
        'othr_cntry_tax_paid_img' => 17,
        'complete_finance_image' => 18,
        'audit_report_img' => 19,
        'pan_image' => 20,
        'previous_return_image' => 21,
        'bank_statement' => 22,
        'adhar_image' => 23,
        'financial_documents' => 24,
        'income_computation' => 25,
        'share_holders' => 26,
        'gst_files' => 27,
    ],
    'ITR_Image_Path' => [
        'image_path' => 'images',
        'thumbHeight' => 768,
        'thumbWeight' => 1024,
        'mediumHeight' => null,
        'mediumWeight' => null,
    ],
    'Profile_Image_Path' => [
        'image_path' => 'profile',
        'thumbHeight' => 768,
        'thumbWeight' => 1024,
        'mediumHeight' => null,
        'mediumWeight' => null,
    ],
    'Corporate_Image_Path' => [
        'image_path' => 'corporate',
        'thumbHeight' => 768,
        'thumbWeight' => 1024,
        'mediumHeight' => null,
        'mediumWeight' => null,
    ],
    'GST_FILES_IMAGES' => [
        'image_path' => 'GST_Files',
        'thumbHeight' => 768,
        'thumbWeight' => 1024,
        'mediumHeight' => null,
        'mediumWeight' => null,
    ]
];
